## 1. Project Information

# ============================================================
## FinSight AI
### Enterprise Financial News Intelligence Platform

### Notebook : 02.1_Dataset_Inspection.ipynb
### Author : Yanshu Patel
### Objective : Inspect all raw datasets before preprocessing.
### This notebook DOES NOT:
#### Clean Data
#### Merge Data
#### Train Models

### This notebook ONLY explores the datasets.
# ============================================================

## 2. Import Libraries

In [13]:
import os
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

## 3. Load Project Paths

In [14]:
PROJECT_ROOT = "/content/drive/MyDrive/FinSight_AI"

RAW_DATA = os.path.join(PROJECT_ROOT, "data/raw")

## 4. Detect Available CSV Files

In [15]:
csv_files = sorted([
    file
    for file in os.listdir(RAW_DATA)
    if file.endswith(".csv")
])

print("CSV Files Found")
for i, file in enumerate(csv_files, start=1):
    print(f"{i}. {file}")

CSV Files Found
1. analyst_ratings_processed.csv
2. raw_analyst_ratings.csv
3. raw_partner_headlines.csv

## 5. Create Dataset Inspection Function

In [16]:
def inspect_dataset(file_path):

    print(f"Dataset : {os.path.basename(file_path)}")

    df = pd.read_csv(file_path, low_memory=False)

    print("\nShape")
    print(df.shape)

    print("\nMemory Usage")
    print(f"{df.memory_usage(deep=True).sum()/1024**2:.2f} MB")

    print("\nColumns")
    print(df.columns.tolist())

    print("\nData Types")
    print(df.dtypes)

    print("\nFirst Five Rows")
    display(df.head())

    print("\nLast Five Rows")
    display(df.tail())

    print("\nMissing Values")
    display(
        df.isnull().sum()
        .sort_values(ascending=False)
    )

    print("\nDuplicate Rows")

    print(df.duplicated().sum())

    print("\nUnique Values")

    display(df.nunique())

    return df

## 6. Inspect Every Dataset

In [17]:
datasets = {}

for file in csv_files:

    path = os.path.join(RAW_DATA, file)

    datasets[file] = inspect_dataset(path)

Dataset : analyst_ratings_processed.csv

Shape
(1400469, 4)

Memory Usage
343.53 MB

Columns
['Unnamed: 0', 'title', 'date', 'stock']

Data Types
Unnamed: 0    float64
title          object
date           object
stock          object
dtype: object

First Five Rows

,Unnamed: 0,title,date,stock
0,0.0,Stocks That Hit 52-Week Highs On Friday,2020-06-05 10:30:00-04:00,A
1,1.0,Stocks That Hit 52-Week Highs On Wednesday,2020-06-03 10:45:00-04:00,A
2,2.0,71 Biggest Movers From Friday,2020-05-26 04:30:00-04:00,A
3,3.0,46 Stocks Moving In Friday's Mid-Day Session,2020-05-22 12:45:00-04:00,A
4,4.0,"B of A Securities Maintains Neutral on Agilent Technologies, Raises Price Target to $88",2020-05-22 11:38:00-04:00,A

Last Five Rows

,Unnamed: 0,title,date,stock
1400464,1413844.0,Top Narrow Based Indexes For August 29,2011-08-29 10:41:00-04:00,ZX
1400465,1413845.0,Recap: Wednesday's Top Percentage Gainers and Losers,2011-06-22 16:44:00-04:00,ZX
1400466,1413846.0,UPDATE: Oppenheimer Color on China Zenix Auto Initiation,2011-06-21 08:26:00-04:00,ZX
1400467,1413847.0,"Oppenheimer Initiates China Zenix At Outperform, $8 PT",2011-06-21 05:59:00-04:00,ZX
1400468,1413848.0,China Zenix Auto International Opens For Trading at $6.00; IPO Price Set at $6.00,2011-05-12 09:36:00-04:00,ZX

Missing Values

stock         2578
Unnamed: 0    1289
date          1289
title            0
dtype: int64

Duplicate Rows
5

Unique Values

Unnamed: 0    1399180
title          843225
date           648859
stock            6192
dtype: int64

Dataset : raw_analyst_ratings.csv

Shape
(1407328, 6)

Memory Usage
634.55 MB

Columns
['Unnamed: 0', 'headline', 'url', 'publisher', 'date', 'stock']

Data Types
Unnamed: 0     int64
headline      object
url           object
publisher     object
date          object
stock         object
dtype: object

First Five Rows

,Unnamed: 0,headline,url,publisher,date,stock
0,0,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/stocks-that-hit-52-week-highs-on-friday,Benzinga Insights,2020-06-05 10:30:54-04:00,A
1,1,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/stocks-that-hit-52-week-highs-on-wednesday,Benzinga Insights,2020-06-03 10:45:20-04:00,A
2,2,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/71-biggest-movers-from-friday,Lisa Levin,2020-05-26 04:30:07-04:00,A
3,3,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/46-stocks-moving-in-fridays-mid-day-session,Lisa Levin,2020-05-22 12:45:06-04:00,A
4,4,"B of A Securities Maintains Neutral on Agilent Technologies, Raises Price Target to $88",https://www.benzinga.com/news/20/05/16095304/b-of-a-securities-maintains-neutral-on-agilent-technologies-raises-price-target-to-88,Vick Meyer,2020-05-22 11:38:59-04:00,A

Last Five Rows

,Unnamed: 0,headline,url,publisher,date,stock
1407323,1413844,Top Narrow Based Indexes For August 29,https://www.benzinga.com/news/11/08/1888782/top-narrow-based-indexes-for-august-29,Monica Gerson,2011-08-29 00:00:00,ZX
1407324,1413845,Recap: Wednesday's Top Percentage Gainers and Losers,https://www.benzinga.com/news/earnings/11/06/1193660/recap-wednesdays-top-percentage-gainers-and-losers,Benjamin Lee,2011-06-22 00:00:00,ZX
1407325,1413846,UPDATE: Oppenheimer Color on China Zenix Auto Initiation,https://www.benzinga.com/analyst-ratings/analyst-color/11/06/1186890/update-oppenheimer-color-on-china-zenix-auto-initiation,BenzingaStaffL,2011-06-21 00:00:00,ZX
1407326,1413847,"Oppenheimer Initiates China Zenix At Outperform, $8 PT",https://www.benzinga.com/analyst-ratings/price-target/11/06/1186025/oppenheimer-initiates-china-zenix-at-outperform-8-pt,Joe Young,2011-06-21 00:00:00,ZX
1407327,1413848,China Zenix Auto International Opens For Trading at $6.00; IPO Price Set at $6.00,https://www.benzinga.com/news/ipos/11/05/1078911/china-zenix-auto-international-opens-for-trading-at-6-00-ipo-price-set-at-6-,Allie Wickman,2011-05-12 00:00:00,ZX

Missing Values

Unnamed: 0    0
headline      0
url           0
publisher     0
date          0
stock         0
dtype: int64

Duplicate Rows
0

Unique Values

Unnamed: 0    1407328
headline       845770
url            883429
publisher        1034
date            39957
stock            6204
dtype: int64

Dataset : raw_partner_headlines.csv

Shape
(1845559, 6)

Memory Usage
806.84 MB

Columns
['Unnamed: 0', 'headline', 'url', 'publisher', 'date', 'stock']

Data Types
Unnamed: 0     int64
headline      object
url           object
publisher     object
date          object
stock         object
dtype: object

First Five Rows

,Unnamed: 0,headline,url,publisher,date,stock
0,2,Agilent Technologies Announces Pricing of $5…… Million of Senior Notes,http://www.gurufocus.com/news/1153187/agilent-technologies-announces-pricing-of-500-million-of-senior-notes,GuruFocus,2020-06-01 00:00:00,A
1,3,Agilent (A) Gears Up for Q2 Earnings: What's in the Cards?,http://www.zacks.com/stock/news/931205/agilent-a-gears-up-for-q2-earnings-whats-in-the-cards?cid=CS-BENZ-FT-analyst_blog|earnings_preview-931205,Zacks,2020-05-18 00:00:00,A
2,4,J.P. Morgan Asset Management Announces Liquidation of Six Exchange-Traded Funds,http://www.gurufocus.com/news/1138923/jp-morgan-asset-management-announces-liquidation-of-six-exchangetraded-funds,GuruFocus,2020-05-15 00:00:00,A
3,5,"Pershing Square Capital Management, L.P. Buys Agilent Technologies Inc, The Howard Hughes Corp, ...",http://www.gurufocus.com/news/1138704/pershing-square-capital-management-lp-buys-agilent-technologies-inc-the-howard-hughes-corp-lowes-inc-sells-chipotle-mexican-grill-inc,GuruFocus,2020-05-15 00:00:00,A
4,6,Agilent Awards Trilogy Sciences with a Golden Ticket at LabCentral,http://www.gurufocus.com/news/1134012/agilent-awards-trilogy-sciences-with-a-golden-ticket-at-labcentral,GuruFocus,2020-05-12 00:00:00,A

Last Five Rows

,Unnamed: 0,headline,url,publisher,date,stock
1845554,1849874,Consumer Cyclical Sector Wrap,https://www.benzinga.com/content/12/08/2846030/consumer-cyclical-sector-wrap,webmaster,2012-08-20 00:00:00,ZX
1845555,1849875,Consumer Cyclical Sector Wrap,https://www.benzinga.com/content/12/07/2767124/consumer-cyclical-sector-wrap,webmaster,2012-07-23 00:00:00,ZX
1845556,1849876,Zacks #5 Rank Additions for Monday - Tale of the Tape,http://www.zacks.com/stock/news/73497/here-are-5-stocks-added-to-the-zacks-5-rank-strong-sell-list-for-monday,Zacks,2012-04-23 00:00:00,ZX
1845557,1849877,4 Stock Strategies From Wall Street: Feb. 9 (Update 1),http://www.thestreet.com/story/11409053/1/4-stock-strategies-from-wall-street-feb-9.html?puc=benzinga&cm_ven=BENZINGA,TheStreet.Com,2012-02-09 00:00:00,ZX
1845558,1849878,4 Stock Strategies From Wall Street: Feb. 9,https://www.benzinga.com/content/thestreet-com/12/02/2330540/4-stock-strategies-from-wall-street-feb-9,webmaster,2012-02-09 00:00:00,ZX

Missing Values

Unnamed: 0    0
headline      0
url           0
publisher     0
date          0
stock         0
dtype: int64

Duplicate Rows
0

Unique Values

Unnamed: 0    1845559
headline       806998
url            889995
publisher          21
date             3731
stock            6552
dtype: int64

## 7. Dataset Summary Table

In [18]:
summary = []

for name, df in datasets.items():

    summary.append({

        "Dataset": name,

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Memory (MB)": round(
            df.memory_usage(deep=True).sum()/1024**2,
            2
        ),

        "Missing Cells": int(df.isnull().sum().sum()),

        "Duplicate Rows": int(df.duplicated().sum())

    })

summary_df = pd.DataFrame(summary)

summary_df

,Dataset,Rows,Columns,Memory (MB),Missing Cells,Duplicate Rows
0,analyst_ratings_processed.csv,1400469,4,344.57,5156,5
1,raw_analyst_ratings.csv,1407328,6,635.59,0,0
2,raw_partner_headlines.csv,1845559,6,810.71,0,0

## 8. Compare Column Names

In [19]:
print("COLUMN COMPARISON")
for name, df in datasets.items():

    print(f"\n{name}")

    print("-"*60)

    for col in df.columns:

        print(col)

COLUMN COMPARISON

analyst_ratings_processed.csv
------------------------------------------------------------
Unnamed: 0
title
date
stock

raw_analyst_ratings.csv
------------------------------------------------------------
Unnamed: 0
headline
url
publisher
date
stock

raw_partner_headlines.csv
------------------------------------------------------------
Unnamed: 0
headline
url
publisher
date
stock

## 9. Date Column Inspection

In [20]:
print("DATE COLUMN CHECK")
for name, df in datasets.items():

    print(f"\n{name}")

    date_columns = [

        col

        for col in df.columns

        if "date" in col.lower()

        or "time" in col.lower()

    ]

    print(date_columns)

DATE COLUMN CHECK

analyst_ratings_processed.csv
['date']

raw_analyst_ratings.csv
['date']

raw_partner_headlines.csv
['date']

## 10. Company/Ticker Column Inspection

In [21]:
print("COMPANY / TICKER COLUMNS")
for name, df in datasets.items():

    print(f"\n{name}")

    cols = [

        col

        for col in df.columns

        if "ticker" in col.lower()

        or "stock" in col.lower()

        or "company" in col.lower()

    ]

    print(cols)

COMPANY / TICKER COLUMNS

analyst_ratings_processed.csv
['stock']

raw_analyst_ratings.csv
['stock']

raw_partner_headlines.csv
['stock']

## 11. Text Column Inspection

In [22]:
print("TEXT COLUMNS")

for name, df in datasets.items():

    print(f"\n{name}")

    cols = [

        col

        for col in df.columns

        if "headline" in col.lower()

        or "title" in col.lower()

        or "text" in col.lower()

    ]

    print(cols)

TEXT COLUMNS

analyst_ratings_processed.csv
['title']

raw_analyst_ratings.csv
['headline']

raw_partner_headlines.csv
['headline']

## 12. Final Observations

In [23]:
print("Inspection Completed Successfully")
print("Next Notebook")
print("03_Data_Cleaning.ipynb")

Inspection Completed Successfully
Next Notebook
03_Data_Cleaning.ipynb