## 1. Imports

In [1]:
import os
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

## 2. Paths

In [2]:
PROJECT_PATH = "/content/drive/MyDrive/FinSight_AI"

DATA_PATH = os.path.join(
    PROJECT_PATH,
    "data"
)

PROCESSED_PATH = os.path.join(
    DATA_PATH,
    "processed"
)

INTELLIGENCE_PATH = os.path.join(
    PROCESSED_PATH,
    "financial_intelligence"
)

PROFILE_PATH = os.path.join(
    PROCESSED_PATH,
    "company_profiles"
)

os.makedirs(
    PROFILE_PATH,
    exist_ok=True
)

## 3. Load Financial Intelligence Dataset

In [4]:
intelligence_df = pd.read_parquet(

    os.path.join(

        INTELLIGENCE_PATH,

        "financial_intelligence_dataset.parquet"

    )

)


print("Financial Intelligence Dataset")


print(intelligence_df.shape)

intelligence_df.head()

Financial Intelligence Dataset
(3215296, 22)

,news_id,headline,url,publisher,published_date,ticker,source,year,month,day,...,headline_length,word_count,has_time,original_headline,clean_character_count,clean_word_count,final_event,market_signal,final_confidence,classification_source
0,1,Stocks That Hit 52-Week Highs On Friday,https://www.benzinga.com/news/20/06/16190091/s...,Benzinga Insights,2020-06-05 14:30:54+00:00,A,analyst,2020,6,5,...,39,7,True,Stocks That Hit 52-Week Highs On Friday,39,7,Market Movement,Neutral,1.0,Rule
1,2,Stocks That Hit 52-Week Highs On Wednesday,https://www.benzinga.com/news/20/06/16170189/s...,Benzinga Insights,2020-06-03 14:45:20+00:00,A,analyst,2020,6,3,...,42,7,True,Stocks That Hit 52-Week Highs On Wednesday,42,7,Market Movement,Neutral,1.0,Rule
2,3,71 Biggest Movers From Friday,https://www.benzinga.com/news/20/05/16103463/7...,Lisa Levin,2020-05-26 08:30:07+00:00,A,analyst,2020,5,26,...,29,5,True,71 Biggest Movers From Friday,29,5,Market Movement,Neutral,1.0,Rule
3,4,46 Stocks Moving In Friday's Mid-Day Session,https://www.benzinga.com/news/20/05/16095921/4...,Lisa Levin,2020-05-22 16:45:06+00:00,A,analyst,2020,5,22,...,44,7,True,46 Stocks Moving In Friday's Mid-Day Session,44,7,Market Movement,Neutral,1.0,Rule
4,5,B of A Securities Maintains Neutral on Agilent...,https://www.benzinga.com/news/20/05/16095304/b...,Vick Meyer,2020-05-22 15:38:59+00:00,A,analyst,2020,5,22,...,87,14,True,B of A Securities Maintains Neutral on Agilent...,87,14,Analyst Rating,Bullish,1.0,Rule

## 4. Dataset Statistics

In [5]:
print("Dataset Statistics")

print(f"Total Headlines : {len(intelligence_df):,}")

print(f"Companies : {intelligence_df['ticker'].nunique():,}")

print(f"Publishers : {intelligence_df['publisher'].nunique():,}")

print(f"Events : {intelligence_df['final_event'].nunique():,}")

print(f"Years : {intelligence_df['year'].nunique():,}")

Dataset Statistics
Total Headlines : 3,215,296
Companies : 6,619
Publishers : 1,047
Events : 30
Years : 12

## 5. Company Basic Statistics

In [6]:
company_basic = (

    intelligence_df

    .groupby("ticker")

    .agg(

        total_news=(

            "news_id",

            "count"

        ),

        first_news=(

            "published_date",

            "min"

        ),

        latest_news=(

            "published_date",

            "max"

        ),

        unique_publishers=(

            "publisher",

            "nunique"

        ),

        avg_headline_length=(

            "headline_length",

            "mean"

        ),

        avg_word_count=(

            "word_count",

            "mean"

        )

    )

    .reset_index()

)

company_basic.head()

,ticker,total_news,first_news,latest_news,unique_publishers,avg_headline_length,avg_word_count
0,A,2328,2009-04-29 00:00:00+00:00,2020-06-05 14:30:54+00:00,126,67.441581,10.307990
1,AA,2908,2009-08-10 00:00:00+00:00,2020-06-09 14:52:15+00:00,205,63.069120,10.222146
2,AAC,366,2010-03-25 00:00:00+00:00,2019-11-12 00:00:00+00:00,20,67.387978,10.592896
3,AADR,32,2012-04-19 00:00:00+00:00,2020-04-30 00:00:00+00:00,5,48.781250,8.000000
4,AAL,494,2011-05-16 00:00:00+00:00,2020-06-10 15:21:01+00:00,21,109.107287,17.010121

## 6. Event Statistics

In [7]:
# Event Statistics
event_stats = (

    pd.crosstab(

        intelligence_df["ticker"],

        intelligence_df["final_event"]

    )

    .reset_index()

)

event_stats.head()

final_event,ticker,Analyst Rating,Bankruptcy,Commodity,Credit Rating,Cryptocurrency,Cybersecurity,Dividend,ESG,Earnings,...,Options Activity,Other,Partnership,Product Launch,Regulatory Approval,Revenue Guidance,Share Buyback,Stock Split,Technical Analysis,Trading Halt
0,A,207,1,52,26,3,6,59,28,604,...,15,104,40,522,33,26,9,0,52,2
1,AA,301,1,242,23,5,2,8,10,516,...,124,117,24,483,7,54,4,12,118,9
2,AAC,18,0,1,1,0,1,1,1,91,...,0,16,1,46,1,1,3,1,12,5
3,AADR,0,0,2,1,0,0,1,0,1,...,0,3,0,12,0,1,0,0,2,0
4,AAL,114,2,4,4,0,1,4,3,65,...,5,46,6,59,6,16,5,2,19,14

## 7. Market Signal Statistics

In [8]:
# Market Signal Statistics
market_stats = (

    pd.crosstab(

        intelligence_df["ticker"],

        intelligence_df["market_signal"]

    )

    .reset_index()

)

market_stats.head()

market_signal ticker  Bearish  Bullish  Mixed  Neutral
0                  A       46      309     10     1963
1                 AA       83      183     10     2632
2                AAC       22       18      5      321
3               AADR        0        1      0       31
4                AAL       35       60      9      390

## 8. Convert Market Counts into Percentages

In [9]:
# Market Signal Percentages
market_percentage = market_stats.copy()

signals = [

    col

    for col in market_percentage.columns

    if col != "ticker"

]

total_signal = market_percentage[signals].sum(axis=1)

for col in signals:

    market_percentage[col + "_pct"] = (

        market_percentage[col]

        / total_signal

        * 100

    ).round(2)

market_percentage.head()

market_signal,ticker,Bearish,Bullish,Mixed,Neutral,Bearish_pct,Bullish_pct,Mixed_pct,Neutral_pct
0,A,46,309,10,1963,1.98,13.27,0.43,84.32
1,AA,83,183,10,2632,2.85,6.29,0.34,90.51
2,AAC,22,18,5,321,6.01,4.92,1.37,87.70
3,AADR,0,1,0,31,0.00,3.12,0.00,96.88
4,AAL,35,60,9,390,7.09,12.15,1.82,78.95

## 9. Confidence Statistics

In [10]:
# Confidence Statistics
confidence_stats = (

    intelligence_df

    .groupby("ticker")

    .agg(

        avg_confidence=(

            "final_confidence",

            "mean"

        ),

        median_confidence=(

            "final_confidence",

            "median"

        ),

        min_confidence=(

            "final_confidence",

            "min"

        ),

        max_confidence=(

            "final_confidence",

            "max"

        ),

        confidence_std=(

            "final_confidence",

            "std"

        )

    )

    .reset_index()

)

confidence_stats.head()

,ticker,avg_confidence,median_confidence,min_confidence,max_confidence,confidence_std
0,A,0.846600,0.78160,0.250,1.0,0.158230
1,AA,0.842717,0.76785,0.333,1.0,0.142895
2,AAC,0.861256,0.85700,0.455,1.0,0.144768
3,AADR,0.768309,0.74000,0.500,1.0,0.111103
4,AAL,0.825818,0.75930,0.333,1.0,0.168170

## 10. Top Publisher Statistics

In [11]:
# Publisher Statistics
publisher_stats = (

    intelligence_df

    .groupby(

        [

            "ticker",

            "publisher"

        ]

    )

    .size()

    .reset_index(

        name="headline_count"

    )

)

top_publishers = (

    publisher_stats

    .sort_values(

        [

            "ticker",

            "headline_count"

        ],

        ascending=[

            True,

            False

        ]

    )

    .groupby("ticker")

    .first()

    .reset_index()

)

top_publishers = top_publishers.rename(

    columns={

        "publisher":"top_publisher",

        "headline_count":"top_publisher_news"

    }

)

top_publishers.head()

  ticker      top_publisher  top_publisher_news
0      A     Benzinga Staff                 427
1     AA      Paul Quintaro                 297
2    AAC      Seeking Alpha                 101
3   AADR      Seeking Alpha                  25
4    AAL  Benzinga Newsdesk                 229

## 11. Activity Statistics

In [12]:
# Activity Statistics
activity_stats = (

    intelligence_df

    .groupby("ticker")

    .agg(

        active_years=(

            "year",

            "nunique"

        ),

        active_months=(

            "month",

            "nunique"

        ),

        active_weekdays=(

            "weekday",

            "nunique"

        ),

        average_news_per_year=(

            "year",

            lambda x: len(x) / x.nunique()

        )

    )

    .reset_index()

)

activity_stats.head()

  ticker  active_years  active_months  active_weekdays  average_news_per_year
0      A            12             12                7             194.000000
1     AA            12             12                7             242.333333
2    AAC             8             12                7              45.750000
3   AADR             8             11                6               4.000000
4    AAL            10             12                6              49.400000

## 12. Company Risk Score

In [13]:
# Company Risk Score
RISK_WEIGHTS = {

    "Fraud":8,

    "Bankruptcy":10,

    "Cybersecurity":6,

    "Litigation":5,

    "Layoffs":4,

    "Credit Rating":3,

    "Regulatory Approval":-2,

    "Dividend":-2,

    "Earnings":-1,

    "Share Buyback":-2

}

risk_score = event_stats.copy()

risk_score["risk_score"] = 0

for event, weight in RISK_WEIGHTS.items():

    if event in risk_score.columns:

        risk_score["risk_score"] += (

            risk_score[event]

            * weight

        )

risk_score = risk_score[

    [

        "ticker",

        "risk_score"

    ]

]

risk_score.head()

final_event ticker  risk_score
0                A        -467
1               AA         -85
2              AAC         -22
3             AADR           0
4              AAL          65

## 13. Intelligence Score

In [14]:
# Company Intelligence Score
intelligence_score = (

    company_basic

    [

        [

            "ticker",

            "total_news",

            "unique_publishers"

        ]

    ]

    .merge(

        confidence_stats[

            [

                "ticker",

                "avg_confidence"

            ]

        ],

        on="ticker"

    )

)

intelligence_score["intelligence_score"] = (

    np.log1p(

        intelligence_score["total_news"]

    )

    *

    intelligence_score["avg_confidence"]

    *

    np.log1p(

        intelligence_score["unique_publishers"]

    )

)

intelligence_score = intelligence_score[

    [

        "ticker",

        "intelligence_score"

    ]

]

intelligence_score.head()

  ticker  intelligence_score
0      A           31.796553
1     AA           35.809422
2    AAC           15.484532
3   AADR            4.813382
4    AAL           15.837993

## 14. Merge All Company Statistics

In [15]:
# Merge All Company Statistics
company_profiles = company_basic.copy()

company_profiles = company_profiles.merge(

    confidence_stats,

    on="ticker",

    how="left"

)

company_profiles = company_profiles.merge(

    top_publishers,

    on="ticker",

    how="left"

)

company_profiles = company_profiles.merge(

    activity_stats,

    on="ticker",

    how="left"

)

company_profiles = company_profiles.merge(

    risk_score,

    on="ticker",

    how="left"

)

company_profiles = company_profiles.merge(

    intelligence_score,

    on="ticker",

    how="left"

)

company_profiles = company_profiles.merge(

    market_percentage,

    on="ticker",

    how="left"

)

company_profiles = company_profiles.merge(

    event_stats,

    on="ticker",

    how="left"

)


print("Company Profile Created")
print(company_profiles.shape)

company_profiles.head()

Company Profile Created
(6619, 58)

,ticker,total_news,first_news,latest_news,unique_publishers,avg_headline_length,avg_word_count,avg_confidence,median_confidence,min_confidence,...,Options Activity,Other,Partnership,Product Launch,Regulatory Approval,Revenue Guidance,Share Buyback,Stock Split,Technical Analysis,Trading Halt
0,A,2328,2009-04-29 00:00:00+00:00,2020-06-05 14:30:54+00:00,126,67.441581,10.307990,0.846600,0.78160,0.250,...,15,104,40,522,33,26,9,0,52,2
1,AA,2908,2009-08-10 00:00:00+00:00,2020-06-09 14:52:15+00:00,205,63.069120,10.222146,0.842717,0.76785,0.333,...,124,117,24,483,7,54,4,12,118,9
2,AAC,366,2010-03-25 00:00:00+00:00,2019-11-12 00:00:00+00:00,20,67.387978,10.592896,0.861256,0.85700,0.455,...,0,16,1,46,1,1,3,1,12,5
3,AADR,32,2012-04-19 00:00:00+00:00,2020-04-30 00:00:00+00:00,5,48.781250,8.000000,0.768309,0.74000,0.500,...,0,3,0,12,0,1,0,0,2,0
4,AAL,494,2011-05-16 00:00:00+00:00,2020-06-10 15:21:01+00:00,21,109.107287,17.010121,0.825818,0.75930,0.333,...,5,46,6,59,6,16,5,2,19,14

## 15. Fill Missing Values

In [16]:
# Fill Missing Values

numeric_columns = company_profiles.select_dtypes(

    include=["number"]

).columns

company_profiles[numeric_columns] = company_profiles[

    numeric_columns

].fillna(0)

company_profiles.head()

,ticker,total_news,first_news,latest_news,unique_publishers,avg_headline_length,avg_word_count,avg_confidence,median_confidence,min_confidence,...,Options Activity,Other,Partnership,Product Launch,Regulatory Approval,Revenue Guidance,Share Buyback,Stock Split,Technical Analysis,Trading Halt
0,A,2328,2009-04-29 00:00:00+00:00,2020-06-05 14:30:54+00:00,126,67.441581,10.307990,0.846600,0.78160,0.250,...,15,104,40,522,33,26,9,0,52,2
1,AA,2908,2009-08-10 00:00:00+00:00,2020-06-09 14:52:15+00:00,205,63.069120,10.222146,0.842717,0.76785,0.333,...,124,117,24,483,7,54,4,12,118,9
2,AAC,366,2010-03-25 00:00:00+00:00,2019-11-12 00:00:00+00:00,20,67.387978,10.592896,0.861256,0.85700,0.455,...,0,16,1,46,1,1,3,1,12,5
3,AADR,32,2012-04-19 00:00:00+00:00,2020-04-30 00:00:00+00:00,5,48.781250,8.000000,0.768309,0.74000,0.500,...,0,3,0,12,0,1,0,0,2,0
4,AAL,494,2011-05-16 00:00:00+00:00,2020-06-10 15:21:01+00:00,21,109.107287,17.010121,0.825818,0.75930,0.333,...,5,46,6,59,6,16,5,2,19,14

## 26. Rank Companies

In [17]:
# Company Rankings
company_profiles["risk_rank"] = (

    company_profiles["risk_score"]

    .rank(

        ascending=False,

        method="dense"

    )

    .astype(int)

)

company_profiles["intelligence_rank"] = (

    company_profiles["intelligence_score"]

    .rank(

        ascending=False,

        method="dense"

    )

    .astype(int)

)

company_profiles.head()

,ticker,total_news,first_news,latest_news,unique_publishers,avg_headline_length,avg_word_count,avg_confidence,median_confidence,min_confidence,...,Partnership,Product Launch,Regulatory Approval,Revenue Guidance,Share Buyback,Stock Split,Technical Analysis,Trading Halt,risk_rank,intelligence_rank
0,A,2328,2009-04-29 00:00:00+00:00,2020-06-05 14:30:54+00:00,126,67.441581,10.307990,0.846600,0.78160,0.250,...,40,522,33,26,9,0,52,2,688,106
1,AA,2908,2009-08-10 00:00:00+00:00,2020-06-09 14:52:15+00:00,205,63.069120,10.222146,0.842717,0.76785,0.333,...,24,483,7,54,4,12,118,9,349,7
2,AAC,366,2010-03-25 00:00:00+00:00,2019-11-12 00:00:00+00:00,20,67.387978,10.592896,0.861256,0.85700,0.455,...,1,46,1,1,3,1,12,5,286,3035
3,AADR,32,2012-04-19 00:00:00+00:00,2020-04-30 00:00:00+00:00,5,48.781250,8.000000,0.768309,0.74000,0.500,...,0,12,0,1,0,0,2,0,264,5665
4,AAL,494,2011-05-16 00:00:00+00:00,2020-06-10 15:21:01+00:00,21,109.107287,17.010121,0.825818,0.75930,0.333,...,6,59,6,16,5,2,19,14,200,2922

## 17. Save Company Profiles

In [18]:
# Save Company Profiles
OUTPUT_FILE = os.path.join(

    PROFILE_PATH,

    "company_profiles.parquet"

)

company_profiles.to_parquet(

    OUTPUT_FILE,

    index=False

)

print("COMPANY PROFILES SAVED")

print(OUTPUT_FILE)

COMPANY PROFILES SAVED
/content/drive/MyDrive/FinSight_AI/data/processed/company_profiles/company_profiles.parquet

## 18. Evaluation

In [19]:
# Top Companies by Intelligence Score
company_profiles.sort_values(

    "intelligence_score",

    ascending=False

)[

    [

        "ticker",

        "total_news",

        "unique_publishers",

        "avg_confidence",

        "risk_score",

        "intelligence_score"

    ]

].head(20)

,ticker,total_news,unique_publishers,avg_confidence,risk_score,intelligence_score
2746,HD,4415,232,0.829553,-297,37.952479
2159,FDX,4358,209,0.831489,-2,37.258004
3982,MS,3157,224,0.839638,201,36.642898
3471,KO,2848,250,0.827965,-303,36.391904
3486,KR,5061,168,0.827025,-608,36.186955
2523,GILD,4938,169,0.820607,-936,35.843719
1,AA,2908,205,0.842717,-85,35.809422
1717,EBAY,3020,200,0.841255,167,35.750971
3699,M,3002,212,0.832631,117,35.744697
3644,LOW,3212,189,0.843545,-490,35.740580
505,AXP,3741,188,0.828504,-406,35.729917
3974,MRK,3302,191,0.837123,-792,35.660865
4435,ORCL,2693,203,0.845425,260,35.513472
1711,EA,3909,176,0.829336,-341,35.506736
6267,VMW,4002,156,0.840013,-104,35.230616
3386,JWN,4361,162,0.823712,-394,35.163542
693,BLK,3886,160,0.837077,-648,35.157051
2633,GRPN,4020,165,0.828431,-87,35.146898
6011,TXN,3814,148,0.850380,-1135,35.091822
3778,MDT,4421,134,0.851852,-1282,35.076352

## 19. Highest Risk Companies

In [20]:
# Highest Risk Companies
company_profiles.sort_values(

    "risk_score",

    ascending=False

)[

    [

        "ticker",

        "risk_score",

        "total_news",

        "Fraud",

        "Bankruptcy",

        "Cybersecurity",

        "Litigation",

        "Layoffs"

    ]

].head(20)

,ticker,risk_score,total_news,Fraud,Bankruptcy,Cybersecurity,Litigation,Layoffs
4527,PCG,2081,3314,21,161,8,74,79
4911,QQQ,2027,2778,0,0,6,2,17
3246,IWM,1806,1127,0,0,3,0,3
4492,PANW,1766,3549,1,0,338,14,36
3600,LL,1706,2306,18,29,1,42,342
1415,CYBR,1561,1792,0,1,305,1,10
5367,SHLD,1295,2519,1,59,14,6,206
1545,DIA,1243,980,1,1,1,1,8
4959,RBS,1220,1730,41,2,16,101,101
4517,PBR,1176,3597,82,2,10,81,79
5688,SYMC,1124,2660,15,0,215,12,33
2705,HACK,1015,411,1,0,170,0,2
2180,FEYE,1010,2010,1,0,204,4,6
1450,DB,952,1909,35,1,22,42,92
2123,FCAU,914,4318,51,2,13,65,94
2622,GREK,899,2467,0,5,12,8,129
1304,CS,897,1981,37,4,16,79,56
2864,HSBC,871,1572,47,0,21,56,75
6572,YHOO,817,3835,16,1,82,17,111
69,ACTG,767,954,0,0,0,173,6

## 20.Summary

In [21]:
summary = pd.DataFrame({

    "Metric":[

        "Companies",

        "Profile Columns",

        "Unique Events",

        "Publishers",

        "Highest Risk Score",

        "Highest Intelligence Score",

        "Output File"

    ],

    "Value":[

        len(company_profiles),

        company_profiles.shape[1],

        intelligence_df["final_event"].nunique(),

        intelligence_df["publisher"].nunique(),

        company_profiles["risk_score"].max(),

        round(company_profiles["intelligence_score"].max(),2),

        os.path.basename(OUTPUT_FILE)

    ]

})

display(summary)

                       Metric                     Value
0                   Companies                      6619
1             Profile Columns                        60
2               Unique Events                        30
3                  Publishers                      1047
4          Highest Risk Score                      2081
5  Highest Intelligence Score                     37.95
6                 Output File  company_profiles.parquet